### ISSUE TITLE
Create and document developer environment

### ISSUE THREAD

**Issue by brylie** [creativecommons/creativecommons-base#68]
## Problem

The project does not currently include instructions for setting up a development environment.

## Description

Add some developer "getting started" steps so it is easy to get the project running locally. Further, a Dockerfile and docker-compose.yml can make it as easy as running `docker-compose up` to get started developing.

If it is useful, include a `devcontainer` configuration to run the development server with all requirements.

## Additional context

It is useful to run the project locally when developing so that you can see the results of changes.

## Implementation

- [x] I would be interested in implementing this feature.

:bulb: One approach would be to add a `develop/` subdirectory in this project with several files:

- docker-compose.yml - Docker services needed to run the project
- Dockerfile - specific configuration environment needed  for the project, such as including composer
- php.conf.ini - PHP configuration variables
- .env - used for environment variables such as database credientials

## :construction: Work-in-progress

Below are some work-in-progress files that are not yet ready to commit to a new branch.

<details>
<summary>docker-compose.yml</summary>

```yml
version: '3'

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - ${IP}:80:80 # change ip if required
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      - ./:/var/www/html/wp-content/themes/creativecommons-base # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
    links:
      - db

  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
      - wp

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      # https://docs.phpmyadmin.net/en/latest/setup.html#docker-environment-variables
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - ${IP}:8080:80
    links:
      - db:db

  db:
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

volumes:
  db_data:
```

</details>

<details>
<summary>php.confi.ini</summary>

```php
file_uploads = On
memory_limit = 500M
upload_max_filesize = 30M
post_max_size = 30M
max_execution_time = 600
```
</details>

<details>
<summary>.env.example</summary>

```sh
IP=127.0.0.1
DB_ROOT_PASSWORD=password
DB_NAME=wordpress
```
</details>

## :memo: Todo

- [ ] determine how best to include Compose in the project
    - compose seems to be used mainly for the Queulat package, which may be deprecated at some point #69 
- [ ] change project structure to better organize the development files and separate them from the theme files

## Resources

- [nezhar / wordpress-docker-compose ](https://github.com/nezhar/wordpress-docker-compose)
